### ISSUE TITLE
Type-constrained functions

### ISSUE THREAD

**Issue by cscherrer** [chakravala/Reduce.jl#22]
Some context... I'd like to be able to manipulate `logpdf`s of `Distribution`s. In most cases this is delegated to a special function. For example,

```
logpdf(Normal(μ, σ), x)
```
calls
```
normlogpdf(μ::Real, σ::Real, x::Number) = normlogpdf(zval(μ, σ, x)) - log(σ)
```
which calls 
```
normlogpdf(z::Number) = -(abs2(z) + log2π)/2
```

These type constraints don't seem Reduce-friendly. Here's a simple test:

```
julia> f(x) = x + 3
f (generic function with 1 method)

julia> f(:x)
:(x + 3)

julia> g(x::Real) = x + 3
g (generic function with 3 methods)

julia> g(:x)
```
This seems to hang.

I could fall back on hacking Distributions.jl or pasting the code in. But it would be pretty great to instead annotate an `RExpr` with a type. Is this possible?

**Comment by chakravala** [comment]
The problem is that your type assertion of `g(x::Real) = x+3` forces the input of `g` to be `<:Real`
```Julia
julia> typeof(:x) <: Real
false
```
So you should not be feeding `:x` into `g` anyway, since `:x` is a `Symbol`, which is not a subtype of `Real`. It's strange that julia does not throw an error, not sure why it hangs. It should error.

Within Reduce, `:x` refers to a variable name, which is not restricted to real values. For example, as explained in the [documentation](https://chakravala.github.io/Reduce.jl/stable/man/10-properties.html#.1-REALVALUED-Declaration-and-Check-1), a declaration is required to specifically make a variable be considered real
```Julia
Reduce.Algebra.realvalued(:x)
```
However, because Reduce uses syntax trees to represent expressions, no type information about the variables being `Real` or not is encoded into the AST. I noticed your discussion thread regarding AST, in which you are concerned with building a model.

> But it would be pretty great to instead annotate an RExpr with a type. Is this possible?

If you require a symbolic type with more domain specific type information, you might want to look at [Rewrite.jl](https://github.com/HarrisonGrodin/Rewrite.jl). Recently I've been thinking about creating symbolic types with additional type annotations, but I'm not sure if I will pursue it myself yet or not.

Technically this is possible with `RExpr` also, but as an interface with `Reduce` there would be some additional complications introduced.

As it is currently designed, Reduce.jl is only intended to work with general AST forms, expression declarations such as `realvalued` need to done with the declarative syntax of REDUCE itself and don't yield any multiple dispatch facilities within the Julia language. Upstream REDUCE itself lacks a type system, and this is one of the issues the upstream developers are currently working on.

**Comment by cscherrer** [comment]
At the moment I'm not too concerned with type information, since most of Distributions.jl has fairly loose typing anyway. I'm really just trying to convince Julia to give me the logpdf as an expression so I can manipulate it algebraically. I may just copy some of these by hand or hack Distributions for now to get things moving forward again.

Thanks for the pointer to the docs. I had started into them, but got pretty confused because some sections are in terms of REDUCE while others are Julia.

And thanks for the pointer to Rewrite.jl. I'll have a look and try to figure out what will be the best overall approach.

**Comment by chakravala** [comment]
REDUCE is entirely it's own programming language, which happens to lack a type system, Reduce.jl simply makes it available to call from Julia

To make it compatible with `Distributions` like that example, you would first need a symbolic type system which is able to dispatch as a subtype of `Real` or you would have to redesign the `Distributions` method dispatch to also handle `Any` or `RExpr` types. Typically, for Julia AST it's best to just use `Any`.

**Comment by chakravala** [comment]
*As [discussed on the Julia discourse topic](https://discourse.julialang.org/t/type-constraints-in-distributions-and-statsfuns/22663/12?u=chakravala), I have now implemented an enhancement to help with this:*

Alright, so I went ahead and [implemented](https://github.com/chakravala/Reduce.jl/commit/33f234cbc9560142b57f7bf95a8041dd0f91152f) the requested feature, which works on `master` branch
```Julia
julia> Reduce.@subtype FakeReal <: Real

julia> FakeReal(R"x+1") + FakeReal(R"y")
y + 1 + x
```
the implementation looks like this at the moment
```Julia
macro subtype(x)
    x.head ≠ :<: && throw(error("$x is not a subtype expression"))
    name = x.args[1]
    Expr(:struct,false,x,Expr(:block,Expr(:(::), :r, :RExpr))) |> eval
    @eval begin
        export $name
        show(io::IO, r::$name) = show(io,r.r)
        extract(r::$name) = r.r
        Algebra.init_subtype($name)
    end
    nothing
end
```
and
```Julia
function init_subtype(name)
    Expr(:block,[:(Base.$i(r::$name...)=$i(extract.(r)...)|>$name) for i ∈ [alg;iops]]...) |> eval
    Expr(:block,[:($i(r::$name...)=$i(extract.(r)...)|>$name) for i ∈ [calculus;cnan;cmat]]...) |> eval
    Expr(:block,[:(Base.$i(r::$name)=$i(extract(r))|>$name) for i ∈ [sbas;[:length]]]...) |> eval
    Expr(:block,[:($i(r::$name)=$i(extract(r))|>$name) for i ∈ [sfun;snan;snum;scom;sint;sran;smat]]...) |> eval
end
```
this provides all of the basic functions from the `Reduce.Algebra` module, but outside that, the new subtypes generated do not have the same treatment ast `RExpr` at the moment
