### ISSUE TITLE
Type-piracy?

### ISSUE THREAD

**Issue by ChrisRackauckas** [chakravala/Reduce.jl#8]
While

>Fully extends the +,-,*,^,/,// operators to work with Symbol and Expr types by building on the new parser features from the previous release, along with many other new capabilities now available.

is a very good feature, it's also type-piracy. I wonder if there's a safer way to implement that without losing the functionality.

**Comment by ChrisRackauckas** [comment]
It's technically unsafe, but seems to work. 

One way to handle it is to have different definitions of `+,-,...` in the namespace of Reduce (`Reduce.+ != Base.+`), and then have a macro that applies this namespacing (`@rops :x^(:x)` -> `Reduce.^(:x,:x)`). It's not too invasive, but still requires a macro. Then if it was a user-choice to import these definitions directly into the namespace (i.e. `using Reduce.Simple` or something like that), it would offer a good middle-ground.

**Comment by chakravala** [comment]
It could also be placed into a separate package, so users can choose to import only the core functionality if they want to and then extend it to whatever level they want by choosing which packages to use.

That is why I set up the new organization [JuliaReducePkg](https://github.com/JuliaReducePkg), since importing the entire library of functions at once is undesirable for most purposes, separate packages will offer specific subsets of extra functionality. It had not occured to me yet that people might want to view the arithmetic operations as separate from the core package as well.

Your proposed approach could be done as well, although it would be more complicated to set up.

There are many other functions too, like `det` for example, that I am also importing, is your concern mainly with the arithmetic operations, or with all such operations?

**Comment by chakravala** [comment]
Forgot to mention that the entire functionality works without having to call any function like `^`, since
```Julia
julia> @rcall x^x
:(x ^ x)

julia> :(x^x)
:(x ^ x)

julia> @eval @rcall $ans
:(x ^ x)
```
is already a feature on the master branch. defining the `^` operation is only done so that it is more convenient to work with expressions arithmetically. However, the rcall command does not need the function to be defined in Julia, it translates it into Reduce command and evaluates it in REDUCE and then translates it back into Julia.

So the `@rops` command you propose is not really necessary.

That only leaves the question of when and how to import things like `^`, it could be put into a separate package module in he JuliaReducePkg org like I said in the previous post. Let me know what you think

**Comment by chakravala** [comment]
Furthermore, to gain insight into what's actually happening behind the scenes, you can use `Reduce.DisplayLog` toggle switch to print the commands that actually are sent to REDUCE
```Julia
julia> Reduce.DisplayLog(true)
true

julia> :x*log(e^:x)
^(e,x)
log(^(e,x))
*(x,x)
:(x ^ 2)

julia> @rcall x*log(e^x)
*(x,log(^(e,x)))
:(x ^ 2)

julia> rcall( :(x*log(e^x)) )
*(x,log(^(e,x)))
:(x ^ 2)
```
When you do that, you can see that it is actually much less efficient to use the extensions of native Julia operations because for each Julia call the AST has to be translated into Reduce, and parsed back into Julia back and forth multiple times, causing increased effort.

However, if you use `rcall` then only a single translation is made, and instead of using Julia's order of operations the Reduce order of operations is used (which is essentially the same).

So, I think what you are proposing leads to the idea that instead of importing the core arithmetic operations from `Base`, to not import them at all, and instead put them into a separate package, so that users can opt-in whether they want to fully extend Julia? Is that what you are proposing then?

**Comment by chakravala** [comment]
The solution from the `SIUnits` packages does not really apply in this case.

In that package, no names are imported from Base. In this package, if I put everything into a sub-module called `Algebra` for example, then even if you don't do `using Reduce.Algebra`, the methods like `+`,`-`, etc are still overloaded because Julia does not support `local import` statements.

This is an issue that I predicted a few months ago, but I received heavy resistance from the core Julia developers for suggesting that a `local import` feature is needed. They were very opposed to me even suggesting that the concept of `local import` is even possible. However, if you were developing a package like this, it would certainly make much sense to have a `local import`, so that functions can be overloaded in a local scope.

The only other solution would be to place that module outside into a separate package. That way, users can choose whether to have any of these functions available or not. So it's either move all these functions into a separate package or keep things the way they are, the only other way out is for the core Julia developers to create the `local import` feature.

**Comment by chakravala** [comment]
The solution from the `SIUnits` packages does not really apply in this case.

In that package, no names are imported from Base. In this package, if I put everything into a sub-module called `Algebra` for example, then even if you don't do `using Reduce.Algebra`, the methods like `+`,`-`, etc are still overloaded because Julia does not support `local import` statements.

This is an issue that I predicted a few months ago, but I received heavy resistance from the core Julia developers for suggesting that a `local import` feature is needed. They were very opposed to me even suggesting that the concept of `local import` is even possible. However, if you were developing a package like this, it would certainly make much sense to have a `local import`, so that functions can be overloaded in a local scope. Maybe @StefanKarpinski can say whether it is possible at this stage.

The only other solution would be to place that module outside into a separate package. That way, users can choose whether to have any of these functions available or not. So it's either move all these functions into a separate package or keep things the way they are, the only other way out is for the core Julia developers to create the `local import` feature.

**Comment by ChrisRackauckas** [comment]
>In that package, no names are imported from Base. In this package, if I put everything into a sub-module called Algebra for example, then even if you don't do using Reduce.Algebra, the methods like +,-, etc are still overloaded because Julia does not support local import statements.

But that's fine. I'm saying you can make it extension as an option, which is perfectly fine (well, mostly). So in the normal module you would shadow Base, and in the submodule you'd extend.

**Comment by chakravala** [comment]
Yes, but have you tried that? If you extend in a submodule, it still overloads all functions in all scopes.

**Comment by ChrisRackauckas** [comment]
Yes, that's exactly what I'm saying. That's just type-piracy. It will always extend in all scopes, but you can make it a choice without making a separate repo.

**Comment by chakravala** [comment]
Unfortunately, if you include that sub-module in the same package, even without `using Reduce.Algebra`, just the fact that the sub-module is defined with `import` statements makes them extend the functions for all namespaces, even though you did not explicitly `using Reduce.Algebra`.

So the only way to make it optional is to place it into an external package, as far as I can tell, or to have something like a `local import`. However, if I am wrong, please provide a working example.

**Comment by ChrisRackauckas** [comment]
Oh shit,

```julia
module Test

  module Test2

    Base.:+(::Symbol,::Symbol) = 2

  end

end

using Test
:x + :x # 2
```

I didn't know it would do that. Then yeah, I guess it has to be another package.

**Comment by chakravala** [comment]
That leaves the question, should that package be called `ReduceAlgebra` or `ReduceBase`? Currently, `ReduceAlgebra` is the name of the meta-package, but the meta-package could be named differently.

**Comment by ChrisRackauckas** [comment]
That package definitely shouldn't be appended `Base` because it's not a `Base` package, which is typically only stub functions, abstract type, and some generic fallbacks (and maybe some basic shared functionality).

**Comment by chakravala** [comment]
To sum up, what will happen is this:
- New package created called `ReduceAlgebra` which will have [args.jl](https://github.com/chakravala/Reduce.jl/blob/master/src/args.jl) and [unary.jl](https://github.com/chakravala/Reduce.jl/blob/master/src/args.jl) in it.
- the [switch.jl](https://github.com/chakravala/Reduce.jl/blob/master/src/switch.jl) definitinos will stay in `Reduce` package, as I think they might be essential to the basic functionality, although it might have to be discussed whether these should be moved over as well.
- The meta-package will be renamed `ReduceExtended`

Essentially, REDUCE switches can be turned on and off for the controlled evaluation of expressions. To make this easy, macros can be used. for example,
```Julia
julia> @factor @rounded x^7-2x+1
:((x + 0.632305570325 + 0.984391731358im) * ((x + 0.632305570325) - 0.984391731358im) * ((x - 0.475255584681) + 0.995903799766im) * ((x - 0.475255584681) - 0.995903799766im) * (x + 1.19003828707) * (x - 1) * (x - 0.504138258362))
```
is essentially the same as using `rcall(:(x^7-2x+1),:factor,:rounded)` where `:factor,:rounded` arguments tell Reduce.jl that you want to toggle those switches for this call.

Another trick I have up my sleeve is that this `@factor @rouned` macro expansion actually reduces to a single `rcall` making it very efficient, even though it is a nested macro call, the macro call actually simplifies itself to a single call automatically. This will be useful in the coming weeks.

As I said, I believe that those definitions could stay with `Reduce` package and not b moved to `ReduceAlgebra` package.

**Comment by chakravala** [comment]
So all definitions in [args.jl](https://github.com/chakravala/Reduce.jl/blob/master/src/args.jl) and [unary.jl](https://github.com/chakravala/Reduce.jl/blob/master/src/args.jl) should be moved to `ReduceAlgebra` or should it be split up in a more thought out way?

**Comment by chakravala** [comment]
Alright, so based on the [discourse discussion](https://discourse.julialang.org/t/possibility-of-local-import-statements-in-future/10611/11), a different solution exists
```Julia
julia> module Foo
           export +
           +(a,b) = Base.:+(a,b)
           +(a::Symbol, b::Symbol) = 2
           algebra() = :(+ = Foo.:+)
       end
Foo

julia> :x+:y
ERROR: MethodError: no method matching +(::Symbol, ::Symbol)

julia> eval(Reduce.algebra())
+ (generic function with 2 methods)

julia> :x+:y
2
```
So I think we will just put everything from args.jl and unary.jl and wrap the overloaded operators like this, and then if people want to load that algebra into their current module, they will use `Reduce.algebra`.

**Comment by chakravala** [comment]
The Type-piracy issue has essentially been resolved at this point on the `force-user` branch.

Since I am not 100% confident that I didn't miss a bug or an error in the dispatch, it is not merged into `master` yet, but if you check out the new branch you should be able to use it without the piracy now.

Specifically, you can now do `using Reduce` without worrying about extending all the operations.

If you do want to locally extend Julia methods with Reduce methods, simply do
```Julia
@force using Reduce.Algebra
```
and then you will have imported all of the extended methods into the local module namespace (this can be done in `Main` or any other `Module`.

Please let me know if you encounter any other issues.

PS: Note that it is no longer possible to rely on the generic Julia algorithms for matrices, since that feature depended on the extensions to the `Base` methods.
